name: CI
on:
  push:
    paths:
      - '.github/workflows/main.yml​'  # 仅监听workflows目录下的文件变更
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running on OCI ARM64 host"
      - run: uname -a
      - run: echo "Test file" > /tmp/github-actions-test.txt
