name: CI
on:
  push:
    paths:
      - '.github/workflows/main.yml​'  # 仅监听workflows目录下的文件变更
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:24.04  # 使用 ARM64 兼容的镜像
    steps:
      - uses: actions/checkout@v4
      - run: echo "Running on OCI ARM64 host"
      - run: uname -a
      - run: echo "122" > /tmp/github-actions-test.txt
